 import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:flutter/material.dart';

Color AppColor = Color(0xFFfb133a);
String url = 'http://www.api.canariapp.com';
double latitude;
double longitude;
String myLocation;
double storeLatitude;
double storeLongitude;
String StoreName;
dynamic deliveryPrice = 0.0;
dynamic olddeliveryPrice = 0.0;
dynamic service_fee = 0.0;
List paymentMethods =[];
bool storeStatus;
int StoreId;
String type;
var TimeStart = '12';
var TimeEnd = '12';
bool Appservice = true;
bool IsPaymentActive = false;
bool CouponActive;
bool shareActive;
bool serviceStatus;
bool isOtpActive;
bool Startwith;
String service_type = '';
String lg = '';
